version: '3.8'

services:
  # 1. Backend API
  backend:
    build: ./hiresphere
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hiresphere:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./hiresphere/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  # 2. Frontend Interface
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # Fixes hot-reload on Windows
    stdin_open: true # Fixes React exit bug
    depends_on:
      - backend

  # 3. Redis (Message Broker)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 4. Celery Worker (Background Tasks)
  celery:
    build: ./hiresphere
    command: celery -A applicantscreeningsystem worker --pool=eventlet -l info
    volumes:
      - ./hiresphere:/app
    depends_on:
      - redis
      - backend
    env_file:
      - ./hiresphere/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0